#! /usr/bin/env python3
# -*- coding:utf-8 -*-
# Copyright 2018-  <linrongbin16@gmail.com>
""" vcmd help document. """

import sys
import os

sys.path.append(".")
import util


def ops_help():
    msg = """[vcmd] lin.vim command line utility.

usage:
    vrg     Searching in current folder by ag/rg.
    vfile   File operations in current folder.
    vgit    Git operations.
    vip     IP calculations.
    vpack   Compress and extract operations.
    vtime   Datetime calculations.
    vgen    Generate configurations.
    vencode Encode and decode.
"""
    print(msg)


if __name__ == "__main__":
    ops_help()
