#! /usr/bin/env python3
# -*- coding:utf-8 -*-
# Copyright 2018-  <linrongbin16@gmail.com>

import sys
import base64
from urllib import parse
import click

sys.path.append(".")
import util


def encode_base64(s):
    b = s.encode("UTF-8")
    b = base64.b64encode(b)
    print(f"{s} => {b.decode('UTF-8')}")


def decode_base64(s):
    b = s.encode("UTF-8")
    b = base64.b64decode(b)
    print(f"{s} => {b.decode('UTF-8')}")


def encode_url(s):
    print(f"{s} => {parse.quote(s)}")


def decode_url(s):
    print(f"{s} => {parse.unquote(s)}")


@click.command()
@click.option("-e",
              "--encode",
              type=click.Choice(["base64", "url"]),
              required=False,
              help="encode text with specified algorithm")
@click.option("-d",
              "--decode",
              type=click.Choice(["base64", "url"]),
              required=False,
              help="decode text with specified algorithm")
@click.argument("args", nargs=-1)
def vencode(encode, decode, args):
    """
Encode/decode text with algorithm

Example:

\b
```
$ vencode -e base64 Hello
Hello => SGVsbG8=
```

\b
```
$ vencode -e base64 'Hello World'
Hello World => SGVsbG8gV29ybGQ=
```
    """
    if len(args) == 0:
        print(f"[vcmd] args is missing")
        return
    if encode:
        if encode == "base64":
            for a in args:
                encode_base64(a)
        elif encode == "url":
            for a in args:
                encode_url(a)
    elif decode:
        if decode == "base64":
            for a in args:
                decode_base64(a)
        elif decode == "url":
            for a in args:
                decode_url(a)
    else:
        print(f"[vcmd] unknown option")


if __name__ == "__main__":
    vencode()
