#! /usr/bin/env python3
# -*- coding:utf-8 -*-
# Copyright 2018-  <linrongbin16@gmail.com>

import sys
import os
import time
import datetime
import getopt
sys.path.append('.')
import util

help_msg = '''Date and time calculations.

usage:
    vtime [option] -d/--datetime [timestamp]    convert [timestamp] from timestamp to datetime string, by default current datetime.
    vtime [option] -t/--timestamp [datetime]    convert [datetime] from datetime string to timestamp, by default current timestamp.

option:
    -u/--utc                                    convert with UTC time, by default using system local time.

flag:
    vtime -h/--help             show help message.
'''


def _help():
    print(help_msg)
    exit(0)


def _datetime(ts):
    dt = datetime.datetime.fromtimestamp(ts)
    print('[vcmd] %s' % (dt.strftime('%Y-%m-%d %H:%M:%S.%f')[0:23]))
    exit(0)


def _timestamp(tm):
    exit(0)


if __name__ == '__main__':
    import pdb
    pdb.set_trace()
    try:
        opts, args = getopt.getopt(sys.argv[1:], 'dth', [
                                   'datetime=', 'timestamp=', 'help'])
        for opt in opts:
            if opt[0] in ('-d', '--datetime'):
                ts = time.time()
                if len(args) > 0:
                    ts = float(args[0])
                _datetime(ts)
            elif opt[0] in ('-t', '--timestamp'):
                dt = datetime.datetime.now()
                if len(opt) > 1:
                    dt = opt[1]
                _timestamp(dt)
        _help()
    except getopt.GetoptError as e:
        print(str(e) + '\n')
        _help()
    except Exception as e:
        print(str(e) + '\n')
