#! /usr/bin/env bash

cmdname=${0##*/}

helpmsg () {
    echo "Brief:"
    echo "    find [word] of current directory recursively"
    echo "Usage:"
    echo "    $cmdname [word]"
    echo "Try again"
    echo ""
}

# error 1: miss repository parameter
if [[ $# -lt 1 ]]; then
    helpmsg
    exit 1
fi

text=$@
ignore=~/.vim/commands/.ignore

ag -w --smart-case --depth -1 -p $ignore "$text" .
