#! /usr/bin/env sh

cmdname=${0##*/}

helpmsg () {
    echo "Brief:"
    echo "    find [word] of current directory recursively"
    echo "Usage:"
    echo "    $cmdname [word]"
    echo "Try again"
    echo ""
}

if [ $# -eq 1 ]; then
    if [ "$1" == "--help" || "$1" == "-h" ]; then
        helpmsg
        exit 1
    fi
fi

# error: miss word parameter
if [ $# -lt 1 ]; then
    helpmsg
    exit 1
fi

text=$@
ignore=~/.vim/commands/ag.ignore

ag -w --smart-case --depth -1 -p $ignore "$text" .
