#! /usr/bin/env sh

cmdname=${0##*/}

helpmsg () {
    echo "Brief:"
    echo "    1. current directory size"
    echo "    2. [file] size"
    echo "    3. [directory] size"
    echo "Usage:"
    echo "    1. $cmdname"
    echo "    2. $cmdname [file]"
    echo "    3. $cmdname [directory]"
    echo "Try again"
    echo ""
}

targetflie=.

if [ $# -eq 1 ]; then
    if [ "$1" == "--help" || "$1" == "-h" ]; then
        helpmsg
        exit 1
    fi
fi

# error 1: miss repository parameter
if [[ $# -ge 1 ]]; then
    targetflie=$1
fi

du -h $targetflie | tail -n 1
