#! /usr/bin/env bash

cmdname=${0##*/}

helpmsg () {
    echo "Brief: Git config commands"
    echo "    1. config [user]"
    echo "    2. config [email]"
    echo "Usage:"
    echo "    1. $cmdname user [user]"
    echo "    2. $cmdname email [email]"
    echo "Try again"
    echo ""
}

# error 1: git comment is a must
if [[ $# -gt 1 ]]; then
    helpmsg
    exit 1
fi

# error 2: not a git repository
if ! git status 1>/dev/null 2>&1; then
    echo "error: git repository not exist"
    helpmsg
    exit 1
fi

cd $(gitroot)

case $1 in
    user)
        shift
        gituser $@
        ;;
    email)
        shift
        gitemail $@
        ;;
    *)
        helpmsg
        exit 1
        ;;
esac
git config --global core.fileMode false
git config --global core.longpaths true
git config core.fileMode false
