#! /usr/bin/env sh

cmdname=${0##*/}

helpmsg () {
    echo "Brief:"
    echo "    git discard everything"
    echo "Usage:"
    echo "    $cmdname"
    echo "Try again"
    echo ""
}

makesure() {
    read yes
    confirm=0
    if [ $yes == "yes" ]; then
        confirm=1
    fi
    if [ $yes == "Yes" ]; then
        confirm=1
    fi
    if [ $yes == "Y" ]; then
        confirm=1
    fi
    if [ $yes == "y" ]; then
        confirm=1
    fi
    if [ $confirm -eq 0 || "$confirm" == "0" ]; then
        echo "error: user not confirm"
        exit 1
    fi
}

if [ $# -eq 1 ]; then
    if [ "$1" == "--help" || "$1" == "-h" ]; then
        helpmsg
        exit 1
    fi
fi

comment="$@"

# error: not a git repository
if ! git status 1>/dev/null 2>&1; then
    echo "error: git repository not exist"
    helpmsg
    exit 1
fi

branch=$(git status | head -n 1 | awk '{print $3}')
echo "[lin-vim] git discard all working copy on: '$branch', path: '$PWD'"
echo -n "[lin-vim] yes? "
makesure

cd $(groot)
for i in $(glistmodifies); do
    git checkout $i
done

