#! /usr/bin/env sh

cmdname=${0##*/}

helpmsg () {
    echo "Brief:"
    echo "    git list all untract files"
    echo "Usage:"
    echo "    $cmdname"
    echo "Try again"
    echo ""
}

if [ $# -eq 1 ]; then
    if [ "$1" == "--help" || "$1" == "-h" ]; then
        helpmsg
        exit 1
    fi
fi

# error: not a git repository
if ! git status 1>/dev/null 2>&1; then
    echo "error: git repository not exist"
    helpmsg
    exit 1
fi

git ls-files -m

untract_flag=0
while IFS='' read -r oneline || [[ -n "$oneline" ]]; do
    oneline="$(echo -e "$oneline" | sed 's/^ *//g' | sed 's/ *$//g')"
    if [ "$oneline" == "Untracked files:" ]; then
        untract_flag=1
        continue
    fi
    if [ "$untract_flag" == "1" && "$oneline" ]; then
        untract_flag=1
        continue
    fi
    if [ "$untract_flag" == "1" ]; then
    fi
done < "git status -uall"
