#! /usr/bin/env sh

cmdname=${0##*/}

helpmsg () {
    echo "Brief:"
    echo "    1. '.gitignore' for All"
    echo "    2. '.gitignore' for C and CXX"
    echo "    3. '.gitignore' for Java"
    echo "    4. '.gitignore' for PHP"
    echo "    5. '.gitignore' for JavaScript"
    echo "    6. '.gitignore' for Golang"
    echo "Usage:"
    echo "    1. $cmdname"
    echo "    2. $cmdname cxx"
    echo "    3. $cmdname java"
    echo "    4. $cmdname php"
    echo "    5. $cmdname js"
    echo "    6. $cmdname go"
    echo "Try again"
    echo ""
}

if [ $# -gt 1 ]; then
    helpmsg
    exit 1
fi

# error: not a git repository
if ! git status 1>/dev/null 2>&1; then
    echo "error: git repository not exist"
    helpmsg
    exit 1
fi

branch=$(git status | head -n 1 | awk '{print $3}')
git pull

cd $(groot)
echo "[lin-vim] update $PWD/.gitignore"
touch .gitignore

ignore_for_common() {
    ignorefile=$1
    echo "#" >> $ignorefile
    echo "# [lin-vim] gomit" >> $ignorefile
    echo "#" >> $ignorefile
    echo ".idea" >> $ignorefile
    echo ".idea/*" >> $ignorefile
    echo "*.iml" >> $ignorefile
    echo ".svn" >> $ignorefile
    echo ".svn/*" >> $ignorefile
    echo ".hg" >> $ignorefile
    echo ".hg/*" >> $ignorefile
    echo "tags" >> $ignorefile
    echo "cscope.out" >> $ignorefile
    echo "cscope.in.out" >> $ignorefile
    echo "cscope.po.out" >> $ignorefile
    echo "cscope.files" >> $ignorefile
    echo "ncscope.out" >> $ignorefile
    echo ".ycm_extra_conf.py" >> $ignorefile
    echo ".vscode" >> $ignorefile
    echo ".vscode/*" >> $ignorefile
    echo "*.vsproj" >> $ignorefile
    echo "*.vsproj/*" >> $ignorefile
    # macOS filesystem
    echo ".DS_Store" >> .gitignore
    echo "*/.DS_Store" >> .gitignore
    echo "*.xcuserdata" >> .gitignore
    echo "*.log" >> .gitignore
}

ignore_for_cxx() {
    ignorefile=$1
    echo "cmake-build-debug" >> $ignorefile
    echo "CMakeCache.txt" >> $ignorefile
    echo "CMakeFiles" >> $ignorefile
    echo "cmake_install.cmake" >> $ignorefile
    echo "install_manifest.txt" >> $ignorefile
    echo "*.slo" >> $ignorefile
    echo "*.lo" >> $ignorefile
    echo "*.o" >> $ignorefile
    echo "*.obj" >> $ignorefile
    echo "*.pro.user" >> $ignorefile
    echo "*.so" >> $ignorefile
    echo "*.so.*" >> $ignorefile
    echo "*.dylib" >> $ignorefile
    echo "*.dylib.*" >> $ignorefile
    echo "*.dll" >> $ignorefile
    echo "*.dll.*" >> $ignorefile
    echo "*.swp" >> $ignorefile
    echo "*.lai" >> $ignorefile
    echo "*.la" >> $ignorefile
    echo "*.a" >> $ignorefile
    echo "*.a.*" >> $ignorefile
    echo "*.lib" >> $ignorefile
    echo "*.lib.*" >> $ignorefile
    echo "*.rdb" >> $ignorefile
    echo "*.exe" >> $ignorefile
    echo "*.out" >> $ignorefile
    echo "*.app" >> $ignorefile
}

ignore_for_java() {
    ignorefile=$1
    echo ".gradle" >> $ignorefile
    echo ".gradle/*" >> $ignorefile
    echo ".m2" >> $ignorefile
    echo ".m2/*" >> $ignorefile
    echo "MANIFEST.MF" >> $ignorefile
    echo "Manifest.mf" >> $ignorefile
    echo "manifest.mf" >> $ignorefile
    echo "*.jar" >> .gitignore
    echo "*.class" >> .gitignore
}

ignore_for_python() {
    ignorefile=$1
    echo "__pycache__" >> .gitignore
    echo "*.pyc" >> .gitignore
}
