#! /usr/bin/env sh

set -e

cmdname=${0##*/}

helpmsg () {
    echo "Brief:"
    echo "    create [branch] and switch"
    echo "Usage:"
    echo "    $cmdname [branch]"
    echo "Try again"
    echo ""
}

# error: missing branch name
if [ $# -ne 1 ]; then
    helpmsg
    exit 1
fi

# error: not a git repository
if ! git status 1>/dev/null 2>&1; then
    echo "error: git repository not exist"
    helpmsg
    exit 1
fi

branch=$1
git checkout -b $branch
