#! /usr/bin/env bash

cmdname=${0##*/}

helpmsg () {
    echo "Brief: Git Repository Commands"
    echo "    1. push"
    echo "    2. pull"
    echo "    3. in"
    echo "    4. root"
    echo "Usage:"
    echo "    1. $cmdname push"
    echo "    2. $cmdname pull"
    echo "    3. $cmdname in"
    echo "    4. $cmdname root"
    echo "Try again"
    echo ""
}

# error 1: git comment is a must
if [[ $# -gt 1 ]]; then
    helpmsg
    exit 1
fi

# error 2: not a git repository
if ! git status 1>/dev/null 2>&1; then
    echo "error: git repository not exist"
    helpmsg
    exit 1
fi

cd $(gitroot)
git add -A .
