#! /usr/bin/env bash

cmdname=${0##*/}

helpmsg() {
    echo "Brief:"
    echo "    unset [host]-[ip] mapping"
    echo "Usage:"
    echo "    $cmdname [host/ip]"
    echo "Try again"
    echo ""
}

makesure() {
    read yes
    confirm=0
    if [[ $yes == "yes" ]]; then
        confirm=1
    fi
    if [[ $yes == "Yes" ]]; then
        confirm=1
    fi
    if [[ $yes == "Y" ]]; then
        confirm=1
    fi
    if [[ $yes == "y" ]]; then
        confirm=1
    fi
    if [[ $confirm -eq 0 || "$confirm" == "0" ]]; then
        echo "error: user not confirm"
        exit 1
    fi
}


if [[ $# -lt 1 ]]; then
    helpmsg
    exit 1
fi

hosts="/etc/hosts"
hosts_new="$hosts.new"
while [[ -f $hosts_new ]]; do
    hosts_new="$hosts_new.new"
done
hosts_old="$hosts.old"

hostname="$(echo -e "$1" | sed 's/^ *//g' | sed 's/ *$//g')"

if ! hostip $hostname 1>/dev/null 2>&1 ; then
    echo "error: $hostname not found"
    exit 1
fi

ipaddr="$(hostip $hostname)"

echo -n "[lin-vim] unset host-ip: '$ipaddr $hostname', yes? "
makesure

sudo touch $hosts
sudo touch $hosts_new
sudo chmod +w,o+w $hosts_new
while IFS='' read -r oneline || [[ -n "$oneline" ]]; do
    onehost="$(echo -e "$oneline" | awk '{print $2}' | sed 's/^ *//g' | sed 's/ *$//g')"
    if [[ ${onehost} != ${hostname} ]]; then
        sudo echo "$oneline" >> $hosts_new
    fi
done < "$hosts"

sudo cp $hosts $hosts_old
sudo mv $hosts_new $hosts
