#! /usr/bin/env bash

cmdname=${0##*/}

helpmsg() {
    echo "Brief:"
    echo "    1. set [host]-[ip] mapping, replace old mapping if exist"
    echo "    2. set [host]-[ip] mapping with [comment], replace old mapping if exist"
    echo "Usage:"
    echo "    1. $cmdname [host] [ip]"
    echo "    2. $cmdname [host] [ip] [comment]"
    echo "Try again"
    echo ""
}

makesure() {
    read yes
    confirm=0
    if [[ $yes == "yes" ]]; then
        confirm=1
    fi
    if [[ $yes == "Yes" ]]; then
        confirm=1
    fi
    if [[ $yes == "Y" ]]; then
        confirm=1
    fi
    if [[ $yes == "y" ]]; then
        confirm=1
    fi
    if [[ $confirm -eq 0 || "$confirm" == "0" ]]; then
        echo "error: user not confirm"
        exit 1
    fi
}

if [[ $# -ne 2 ]]; then
    helpmsg
    exit 1
fi

hostname="$1"
ipaddr="$2"

echo -n "[lin-vim] set host-ip: '$ipaddr $hostname', yes? "
makesure

if ! hostip $hostname 1>/dev/null 2>&1; then
    echo "info: $hostname already exist, replace it"
    hostunset $hostname
fi
sudo chmod +w,o+w /etc/hosts
sudo echo "$ipaddr\t$hostname" >> /etc/hosts
