#! /usr/bin/env bash

cmdname=${0##*/}

helpmsg() {
    echo "Brief:"
    echo "    1. set [ip]-[host] mapping, replace old mapping if exist"
    echo "    2. set [ip]-[host] mapping with [comment], replace old mapping if exist"
    echo "Usage:"
    echo "    1. $cmdname [ip] [hostname]"
    echo "    2. $cmdname [ip] [hostname] [comment]"
    echo "Try again"
    echo ""
}

makesure() {
    read yes
    confirm=0
    if [[ $yes == "yes" ]]; then
        confirm=1
    fi
    if [[ $yes == "Yes" ]]; then
        confirm=1
    fi
    if [[ $yes == "Y" ]]; then
        confirm=1
    fi
    if [[ $yes == "y" ]]; then
        confirm=1
    fi
    if [[ $confirm -eq 0 || "$confirm" == "0" ]]; then
        echo "error: user not confirm"
        exit 1
    fi
}

if [[ $# -ne 2 ]]; then
    helpmsg
    exit 1
fi

ipaddr="$1"
hostname="$2"

if ! hostip $hostname 1>/dev/null 2>&1; then
    echo "error: $hostname already exist, use 'hostunset $hostname' to remove it first"
    exit 1
fi

echo -n "[lin-vim] set host-ip: '$ipaddr   $hostname', yes? "
makesure
sudo chmod +w,o+w /etc/hosts
sudo echo "$ipaddr  $hostname" >> /etc/hosts
