#! /usr/bin/env bash

cmdname=${0##*/}

helpmsg() {
    echo "Brief:"
    echo "    1. list all ip-which which is using"
    echo "    2. find specified [ip] which is using"
    echo "Usage:"
    echo "    1. $cmdname"
    echo "    2. $cmdname [ip]"
    echo "Try again"
    echo ""
}

if [[ $(sysname) == "Darwin" ]]; then
    if [[ $# -lt 1 ]]; then
        sudo netstat -antl
    elif [[ $# -eq 1 ]]; then
        sudo netstat -antl | grep "$1"
    else
        helpmsg
        exit 1
    fi
else
    if [[ $# -lt 1 ]]; then
        sudo netstat -antp
    elif [[ $# -eq 1 ]]; then
        sudo netstat -antp | grep "$1"
    else
        helpmsg
        exit 1
    fi
fi
