#! /usr/bin/env bash

cmdname=${0##*/}

helpmsg() {
    echo "Brief:"
    echo "    get ip (not 127.0.0.1) of current machine"
    echo "Usage:"
    echo "    $cmdname"
    echo "Try again"
    echo ""
}

if [[ $# -gt 0 ]]; then
    helpmsg
    exit 1
fi

if [[ "$(uname)" != "Darwin" ]]; then
    ip addr | grep 'state UP' -A2 | tail -n1 | awk '{print $2}' | cut -f1  -d'/'
else
    ifconfig en0 | grep inet | grep -v inet6 | cut -d ' ' -f2
fi
