#! /usr/bin/env bash

cmdname=${0##*/}

helpmsg() {
    echo "Brief:"
    echo "    transform ipv4 from [uint32] to string"
    echo "Usage:"
    echo "    $cmdname [uint32]"
    echo "Try again"
    echo ""
}

converter() {
    echo -n $(($(($(($((${1}/256))/256))/256))%256)).
    echo -n $(($(($((${1}/256))/256))%256)).
    echo -n $(($((${1}/256))%256)).
    echo $((${1}%256))
}

if [[ $# -lt 1 ]]; then
    helpmsg
    exit 1
fi

ipaddr="$1"
converter "$ipaddr"
