#! /usr/bin/env bash

cmdname=${0##*/}

helpmsg () {
    echo "Brief:"
    echo "    create hard [link] for [file]"
    echo "Usage:"
    echo "    $cmdname [file] [link]"
    echo "Try again"
    echo ""
}

# error 1: miss parameter
if [[ $# -lt 2 ]]; then
    helpmsg
    exit 1
fi

sourcefile="$1"
targetfile="$2"

if [[ -x "$targetfile" ]]; then
    echo "[lin-vim] backup '$targetfile' to '$targetfile.old'"
    mv "$targetfile" "$targetfile.old"
fi

ln "$sourcefile" "$targetfile"
