#! /usr/bin/env bash

cmdname=${0##*/}

helpmsg() {
    echo "Brief:"
    echo "    transform [number] from 2-binary to 10-decimal"
    echo "Usage:"
    echo "    $cmdname [number]"
    echo "Try again"
    echo ""
}

# error 1: missing parameter
if [[ $# -lt 1 ]]; then
    helpmsg
    exit 1
fi

number=$1
echo "ibase=2;obase=1010; $number" | bc
