#! /usr/bin/env bash

cmdname=${0##*/}

helpmsg() {
    echo "Brief:"
    echo "    transform [number] from 10-decimal to 16-heximal"
    echo "Usage:"
    echo "    $cmdname [number]"
    echo "Try again"
    echo ""
}

# error 1: missing parameter
if [[ $# -lt 1 ]]; then
    helpmsg
    exit 1
fi

number=$1
echo "ibase=10;obase=16; $number" | bc
