#! /usr/bin/env bash

cmdname=${0##*/}

helpmsg () {
    echo "Brief:"
    echo "    1. show process network state by [name]"
    echo "    2. show process network state by [pid]"
    echo "Usage:"
    echo "    1. $cmdname [name]"
    echo "    2. $cmdname [pid]"
    echo "Try again"
    echo ""
}

# error: missing parameter
if [[ $# -lt 1 ]]; then
    helpmsg
    exit 1
fi

proc="$1"

if [[ $proc =~ ^[0-9]+$ ]]; then
    sudo netstat -antp | grep $proc
else
    for eachpid in $(ps aux | grep "$proc" \
                            | grep -v "grep \-\-color\=auto" \
                            | grep -v "proclist" \
                            | grep -v "grep $proc" \
                            | awk '{print $2}'); do
        sudo netstat -antp | grep "$eachpid"
    done
fi
