#! /usr/bin/env bash

cmdname=${0##*/}

helpmsg () {
    echo "Brief:"
    echo "    1. list all running process"
    echo "    2. find process by [name]"
    echo "    3. find process by [pid]"
    echo "Usage:"
    echo "    1. $cmdname"
    echo "    2. $cmdname [name]"
    echo "    3. $cmdname [pid]"
    echo "Try again"
    echo ""
}

saveheader="$(ps aux | head -n1)"

if [[ $# -lt 1 ]]; then
    echo ""
    ps aux
    echo "$saveheader"
    echo ""
elif [[ $# -eq 1 ]]; then
    proc="$1"
    echo ""
    echo "$saveheader"
    ps aux  | grep "$proc" \
            | grep -v "grep \-\-color\=auto" \
            | grep -v "proclist" \
            | grep -v "grep $proc"
    echo "$saveheader"
    echo ""
else
    # error: too many parameter
    helpmsg
    exit 1
fi
