#! /usr/bin/env bash

cmdname=${0##*/}

helpmsg() {
    echo "Brief:"
    ip addr | grep 'state UP' -A2 | tail -n1 | awk '{print $2}' | cut -f1  -d'/'
    echo "    1. copy [j] currenty directory to remote host2"
    echo "    2. copy [directory] with scp"
    echo "    3. copy [file] with scp"
    echo "Usage:"
    echo "    1. $cmdname [user1]@[host1] [user2]@[host2]"
    echo "    2. $cmdname [user1]@[host1]:[srcfile] [user2]@[host2/ip2]:[destfile]"
    echo "    3. $cmdname [user1]@[host1]:[srcfile] [user2]@[host2/ip2]:[destfile]"
    echo "try again"
}

# error 1: miss parameter
if [[ $# -lt 2 ]]; then
    helpmsg
    exit 1
fi

src=$1
dest=$2

scp -r $src $dest
