#! /usr/bin/env bash

cmdname=${0##*/}

helpmsg() {
    echo "Brief:"
    echo "    generate ~/.ssh/id_rsa, ~/.ssh/id_rsa.pub for [email]"
    echo "Usage:"
    echo "    $cmdname [email]"
    echo "Try again"
    echo ""
}

makesure() {
    read yes
    confirm=0
    if [ $yes == "yes" ]; then
        confirm=1
    fi
    if [ $yes == "Yes" ]; then
        confirm=1
    fi
    if [ $yes == "Y" ]; then
        confirm=1
    fi
    if [ $yes == "y" ]; then
        confirm=1
    fi
    if [ $confirm -eq 0 || "$confirm" == "0" ]; then
        echo "error: user not confirm"
        exit 1
    fi
}

if [ $# -lt 1 ]; then
    helpmsg
    exit 1
fi
myemail=$1

# overwrite id_rsa id_rsa.pub
if [ ! -d ~/.ssh ]; then
    mkdir -p ~/.ssh
fi

if [ -f ~/.ssh/id_rsa || -f ~/.ssh/id_rsa.pub ]; then
    echo -n "[lin-vim] id_rsa or id_rs.pub already exist, overwrite? "
    makesure
    if [ -f ~/.ssh/id_rsa ]; then
        mv ~/.ssh/id_rsa ~/.ssh/id_rsa.bak
    fi
    if [ -f ~/.ssh/id_rsa.pub ]; then
        mv ~/.ssh/id_rsa.pub ~/.ssh/id_rsa.pub.bak
    fi
fi

touch ~/.ssh/known_hosts
touch ~/.ssh/authorized_keys
chmod 600 ~/.ssh/authorized_keys
chmod 700 -R ~/.ssh

echo "[lin-vim] generate id_rsa for \"$myemail\", type ENTER if you don't need passphrase"
ssh-keygen -t rsa -b 4096 -C "$myemail"
chmod 600 ~/.ssh/id_rsa
chmod 644 ~/.ssh/id_rsa.pub
ssh-add ~/.ssh/id_rsa
echo ""
echo "[lin-vim] your ~/.ssh/id_rsa.pub:"
cat ~/.ssh/id_rsa.pub


# 1. login without password for github
# $ ssh-keygen -t rsa -b 4096 -C "myemail@gmail.com"
#  Generating public/private rsa key pair.
#  Enter file in which to save the key (~/.ssh/id_rsa):
#  Enter passphrase (empty for no passphrase):
#  Enter same passphrase again:
# public key: ~/.ssh/id_rsa.pub, private key: ~/.ssh/id_rsa
# save public key to github, and you can login via 'git@github.com'
# reference:
# https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent/

# 2. login without password for linux
# use: ~/.ssh/id_rsa.pub and ~/.ssh/id_rsa generated by the 1st step
# cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
# chmod 700 -R ~/.ssh
# chmod 600 ~/.ssh/authorized_keys
# chmod 600 ~/.ssh/id_rsa
# chmod 644 ~/.ssh/id_rsa.pub
# ssh-add ~/.ssh/id_rsa
