#! /usr/bin/env bash

cmdname=${0##*/}

helpmsg() {
    echo "help: execute command with ssh"
    echo "usage: $cmdname [user1]@[host1/ip1]:[srcfile] [user2]@[host2/ip2]:[destfile]"
    echo "try again"
}

# error 1: miss parameter
if [[ $# -lt 2 ]]; then
    helpmsg
    exit 1
fi

hostname=$1
shift

ssh -e "$myname@$hostname" "$@"
