#! /usr/bin/env bash

cmdname=${0##*/}

helpmsg () {
    echo "Brief:"
    echo "    1. compress current directory"
    echo "    2. compress [file/directory]"
    echo "Usage:"
    echo "    1. $cmdname"
    echo "    2. $cmdname [file/directory]"
    echo "Try again"
    echo ""
}


if [[ $# -lt 1 ]]; then
    curdir=$(pwd)
    gzfile="$curdir.tar.gz"
    if [[ -f $gzfile ]]; then
        mv $gzfile "$gzfile.old"
    fi
    cd ..
    tar -zcvf "$gzfile" "$curdir"
else
    for i in $@; do
        gzfile="$i.tar.gz"
        if [[ -f $gzfile ]]; then
            mv $gzfile "$gzfile.old"
        fi
        tar -zcvf "$gzfile" "$i"
    done
fi
