#! /usr/bin/env bash

cmdname=${0##*/}

helpmsg() {
    echo "Brief:"
    echo "    1. transform [yyyy-mm-dd] (year-mon-day) to utc timestamp(seconds)"
    echo "    2. transform [yyyy-mm-dd HH:MM:SS] (year-mon-day hour:min:sec) to utc timestamp(seconds)"
    echo "Usage:"
    echo "    1. $cmdname [yyyy-mm-dd]"
    echo "    2. $cmdname [yyyy-mm-dd HH:MM:SS]"
    echo "Try again"
    echo ""
}

if [[ $# -lt 1 ]]; then
    helpmsg
    exit 1
fi

if [[ $# -gt 2 ]]; then
    helpmsg
    exit 1
fi

datetime="$@"

if [[ $(uname) == "Darwin" ]]; then
    if [[ $# -lt 2 ]]; then
        date -f "yyyy-mm-dd" "$datetime" "+%s"
    else
        date -f "yyyy-mm-dd HH:MM:ss" "$datetime" "+%s"
    fi
else
    date -d "$datetime" "+%s"
fi
